Update `WitnessField`
zkFold/zkfold-base pull request #245
Opened 2024-09-05 22:16 UTC by TurtlePU

This PR updates `WitnessField` typealias by replacing `BinaryExpansion` constraint with a conversion to the "unbounded natural numbers" type which is a `EuclideanDomain`. Also some minor improvements along the way.

Branches out from #244, so maybe this one has to be merged first.

2024-09-06 06:40 UTC, TurtlePU commented
Tests fail for `UInt`'s `Ord` instance and `divMod`, investigating
Most probably something to do with variable generation again

2024-09-06 20:05 UTC, TurtlePU commented
@vlasin, all tests pass except "Conversion to Plonk constraints and back" test because in case when some of variables are `Nothing`, constraints are not equal (and don't have to be, according to the definition of a constraint)
So this is not in scope of this PR but has to be fixed in a separate PR

2024-09-06 20:06 UTC, TurtlePU commented
@echatav, can you take a look at this PR? It is ready.

2024-09-06 20:32 UTC, echatav requested changes
Looks good to me, but let's take the time now to rename one class?

2024-09-06 20:32 UTC, echatav commented on src/ZkFold/Base/Algebra/Basic/Class.hs
>  class Semiring a => EuclideanDomain a where
Let's rename this to `SemiEuclidean` in this PR? `Euclidean(Domain)` should be `Ring` + `SemiEuclidean` + `eea`

2024-09-06 21:44 UTC, echatav approved these changes
:shipit:

2024-09-06 21:48 UTC, echatav commented on src/ZkFold/Base/Algebra/Basic/Class.hs
> +be endowed with at least one function @f : a\{0} -> R+@ s.t. if @x@ and @y@ are
<img width="1104" alt="Screenshot 2024-09-06 at 2 47 49 PM" src="https://github.com/user-attachments/assets/0272cfcd-d7ea-4351-aad0-29913ce3aad6">

2024-09-08 17:21 UTC, vlasin commented
> @vlasin, all tests pass except "Conversion to Plonk constraints and back" test because in case when some of variables are `Nothing`, constraints are not equal (and don't have to be, according to the definition of a constraint) So this is not in scope of this PR but has to be fixed in a separate PR

Could you elaborate? Why don't they have to be equal?

2024-09-08 19:13 UTC, TurtlePU commented
> Could you elaborate? Why don't they have to be equal?

Because if one of the inputs is constant, evaluating Plonk constraint into polynomial loses information which one of them. For example,

1. The constraint `C` is `1 x c(1) + 0 x + 0 c(1) + (-1) z + 0 = 0` where `c(1)` is the placeholder constant input
2. Evaluated as a polynomial, this is `x - z = 0`
3. As a Plonk constraint, this can be represented:
  * as `C`
  * as `0 x c(1) + 1 x + 0 c(1) + (-1) z + 0 = 0`
  * as `0 c(1) x + 0 c(1) + 1 x + (-1) z + 0 = 0`
  * as `0 c(1) z + 0 c(1) + (-1) z + 1 x + 0 = 0`
  * as `0 z c(1) + (-1) z + 0 c(1) + 1 x + 0 = 0`
  * also in a myriad more ways as `a x c(1) + (1 - a) x + 0 c(1) + (-1) z + 0 = 0`
 
Before #244, the possibility of introducing `c(1)` in arbitrary Plonk constraint was negligible, so this was not caught before. Also, analogously, the same issue arises with linear constraints of the form `x + y - z = 0` because there are 6 options how this constraint can be represented, but this one again has a negligible probability in our tests because for this, we need to have the coefficient near `xy` to equal `0`.

2024-09-08 20:00 UTC, vlasin commented
Ok, I agree to fix it in another PR.

2024-09-08 20:00 UTC, merged