feat: add quick testing scenario with flag
zkFold/zkfold-base pull request #300
Opened 2024-10-14 06:52 UTC by diS3e

Added flag to disable all slow tests

2024-10-14 15:31 UTC, echatav requested changes
Can you remove commented code and if possible, make the tests run with the fast flag turned on in CI?

2024-10-15 00:21 UTC, TurtlePU requested changes
I'd prefer the division into slow/fast tests to be more granular: we'd still like to test at least some of the simpler properties of proof protocols in CI, for example.

To achieve this, I'd do it via command line arguments specified in a CI: we can name slow tests as "...something something... SLOW" and skip them with [`--skip=SLOW` Hspec argument](https://hspec.github.io/options.html#specifying-options-in-config-fi%E2%80%8C%E2%80%8Bles).

2024-10-29 15:04 UTC, TurtlePU approved these changes

2024-10-29 16:24 UTC, echatav approved these changes
lgtm

2024-10-29 17:19 UTC, merged